name = "system_random_example"
description = "Example of system_random usage"
version = "0.0.0"

authors = ["Anton Fediushin"]
maintainers = ["Anton Fediushin <imantonmeep@gmail.com>"]
maintainers-logins = ["AntonMeep"]

executables = ["system_random_example"]

[configuration]
disabled = true

[[depends-on]]
system_random = "*"

[[pins]]
system_random = { path = "../" }
