name: Build

on:
  push:
    branches: [ master ]
  release:
    types: [created]

jobs:
  build:
    name: Building on ${{matrix.os}} using ${{matrix.compiler}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        compiler: [fsf, community]
        exclude:
          - os: windows-latest
            compiler: fsf
          - os: macos-latest
            compiler: fsf
    steps:
    - uses: actions/checkout@v2

    - name: Install toolchain
      uses: ada-actions/toolchain@ce2021
      with:
        distrib: ${{matrix.compiler}}
        target: native

    - name: Install Alire
      uses: alire-project/setup-alire@v1
      with:
        toolchain: "gnat_external"

    - name: Build debug, static
      run: |
        alr build
        -XSYSTEM_RANDOM_LIBRARY_TYPE=static
        -XSYSTEM_RANDOM_COMPILE_CHECKS=enabled
        -XSYSTEM_RANDOM_RUNTIME_CHECKS=enabled
        -XSYSTEM_RANDOM_STYLE_CHECKS=enabled
        -XSYSTEM_RANDOM_CONTRACTS=enabled
        -XSYSTEM_RANDOM_BUILD_MODE=debug
